# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_communication/chassisControl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class chassisControl(genpy.Message):
  _md5sum = "ba44848e12b315b92df95a3f875577ab"
  _type = "robot_communication/chassisControl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 导航发布的消息
#全局x轴线速度
float32 xSpeed 
#全局y轴线速度
float32 ySpeed
#底盘角度
float32 chassisAngle
#底盘角速度
float32 chassisGyro
# 时间戳
uint32 timeStamp
# 标志位局部控制还是全局控制
bool globalOrlocal"""
  __slots__ = ['xSpeed','ySpeed','chassisAngle','chassisGyro','timeStamp','globalOrlocal']
  _slot_types = ['float32','float32','float32','float32','uint32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       xSpeed,ySpeed,chassisAngle,chassisGyro,timeStamp,globalOrlocal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(chassisControl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.xSpeed is None:
        self.xSpeed = 0.
      if self.ySpeed is None:
        self.ySpeed = 0.
      if self.chassisAngle is None:
        self.chassisAngle = 0.
      if self.chassisGyro is None:
        self.chassisGyro = 0.
      if self.timeStamp is None:
        self.timeStamp = 0
      if self.globalOrlocal is None:
        self.globalOrlocal = False
    else:
      self.xSpeed = 0.
      self.ySpeed = 0.
      self.chassisAngle = 0.
      self.chassisGyro = 0.
      self.timeStamp = 0
      self.globalOrlocal = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4fIB().pack(_x.xSpeed, _x.ySpeed, _x.chassisAngle, _x.chassisGyro, _x.timeStamp, _x.globalOrlocal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.xSpeed, _x.ySpeed, _x.chassisAngle, _x.chassisGyro, _x.timeStamp, _x.globalOrlocal,) = _get_struct_4fIB().unpack(str[start:end])
      self.globalOrlocal = bool(self.globalOrlocal)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4fIB().pack(_x.xSpeed, _x.ySpeed, _x.chassisAngle, _x.chassisGyro, _x.timeStamp, _x.globalOrlocal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.xSpeed, _x.ySpeed, _x.chassisAngle, _x.chassisGyro, _x.timeStamp, _x.globalOrlocal,) = _get_struct_4fIB().unpack(str[start:end])
      self.globalOrlocal = bool(self.globalOrlocal)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4fIB = None
def _get_struct_4fIB():
    global _struct_4fIB
    if _struct_4fIB is None:
        _struct_4fIB = struct.Struct("<4fIB")
    return _struct_4fIB
