# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_communication/localizationInfoBroadcast.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class localizationInfoBroadcast(genpy.Message):
  _md5sum = "93de7300af4a3e98ca0a4ec3c9466b01"
  _type = "robot_communication/localizationInfoBroadcast"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 定位消息广播需要数据
# 全局x位置
float32 xPosition
# 全局y位置
float32 yPosition
#全局x轴线速度
float32 xSpeed 
#全局y轴线速度
float32 ySpeed
#车体x加速度
float32 xAccel 
#车体y加速度
float32 yAccel
#底盘角度
float32 chassisAngle
#底盘角速度
float32 chassisGyro
# 时间戳
uint32 timeStamp

"""
  __slots__ = ['xPosition','yPosition','xSpeed','ySpeed','xAccel','yAccel','chassisAngle','chassisGyro','timeStamp']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       xPosition,yPosition,xSpeed,ySpeed,xAccel,yAccel,chassisAngle,chassisGyro,timeStamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(localizationInfoBroadcast, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.xPosition is None:
        self.xPosition = 0.
      if self.yPosition is None:
        self.yPosition = 0.
      if self.xSpeed is None:
        self.xSpeed = 0.
      if self.ySpeed is None:
        self.ySpeed = 0.
      if self.xAccel is None:
        self.xAccel = 0.
      if self.yAccel is None:
        self.yAccel = 0.
      if self.chassisAngle is None:
        self.chassisAngle = 0.
      if self.chassisGyro is None:
        self.chassisGyro = 0.
      if self.timeStamp is None:
        self.timeStamp = 0
    else:
      self.xPosition = 0.
      self.yPosition = 0.
      self.xSpeed = 0.
      self.ySpeed = 0.
      self.xAccel = 0.
      self.yAccel = 0.
      self.chassisAngle = 0.
      self.chassisGyro = 0.
      self.timeStamp = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8fI().pack(_x.xPosition, _x.yPosition, _x.xSpeed, _x.ySpeed, _x.xAccel, _x.yAccel, _x.chassisAngle, _x.chassisGyro, _x.timeStamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.xPosition, _x.yPosition, _x.xSpeed, _x.ySpeed, _x.xAccel, _x.yAccel, _x.chassisAngle, _x.chassisGyro, _x.timeStamp,) = _get_struct_8fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8fI().pack(_x.xPosition, _x.yPosition, _x.xSpeed, _x.ySpeed, _x.xAccel, _x.yAccel, _x.chassisAngle, _x.chassisGyro, _x.timeStamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.xPosition, _x.yPosition, _x.xSpeed, _x.ySpeed, _x.xAccel, _x.yAccel, _x.chassisAngle, _x.chassisGyro, _x.timeStamp,) = _get_struct_8fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8fI = None
def _get_struct_8fI():
    global _struct_8fI
    if _struct_8fI is None:
        _struct_8fI = struct.Struct("<8fI")
    return _struct_8fI
