# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_communication/sensorData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class sensorData(genpy.Message):
  _md5sum = "2b6cc02982ebe7cd38d12aed40230509"
  _type = "robot_communication/sensorData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#接收到下位机发送的消息，轮速计、IMU、时间戳等
#局部速度
float32 local_x_Veloc
float32 local_y_Veloc
#局部加速度
float32 local_x_Accel
float32 local_y_Accel
#yaw轴数值
float32 yaw
#时间戳 10us是时间戳的分辨率
uint32 timeStamp_10us
"""
  __slots__ = ['local_x_Veloc','local_y_Veloc','local_x_Accel','local_y_Accel','yaw','timeStamp_10us']
  _slot_types = ['float32','float32','float32','float32','float32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       local_x_Veloc,local_y_Veloc,local_x_Accel,local_y_Accel,yaw,timeStamp_10us

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sensorData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.local_x_Veloc is None:
        self.local_x_Veloc = 0.
      if self.local_y_Veloc is None:
        self.local_y_Veloc = 0.
      if self.local_x_Accel is None:
        self.local_x_Accel = 0.
      if self.local_y_Accel is None:
        self.local_y_Accel = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.timeStamp_10us is None:
        self.timeStamp_10us = 0
    else:
      self.local_x_Veloc = 0.
      self.local_y_Veloc = 0.
      self.local_x_Accel = 0.
      self.local_y_Accel = 0.
      self.yaw = 0.
      self.timeStamp_10us = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5fI().pack(_x.local_x_Veloc, _x.local_y_Veloc, _x.local_x_Accel, _x.local_y_Accel, _x.yaw, _x.timeStamp_10us))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.local_x_Veloc, _x.local_y_Veloc, _x.local_x_Accel, _x.local_y_Accel, _x.yaw, _x.timeStamp_10us,) = _get_struct_5fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5fI().pack(_x.local_x_Veloc, _x.local_y_Veloc, _x.local_x_Accel, _x.local_y_Accel, _x.yaw, _x.timeStamp_10us))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.local_x_Veloc, _x.local_y_Veloc, _x.local_x_Accel, _x.local_y_Accel, _x.yaw, _x.timeStamp_10us,) = _get_struct_5fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5fI = None
def _get_struct_5fI():
    global _struct_5fI
    if _struct_5fI is None:
        _struct_5fI = struct.Struct("<5fI")
    return _struct_5fI
