// Generated by gencpp from file robot_communication/Bspline.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_BSPLINE_H
#define ROBOT_COMMUNICATION_MESSAGE_BSPLINE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace robot_communication
{
template <class ContainerAllocator>
struct Bspline_
{
  typedef Bspline_<ContainerAllocator> Type;

  Bspline_()
    : order(0)
    , traj_id(0)
    , knots()
    , pts()
    , start_time()  {
    }
  Bspline_(const ContainerAllocator& _alloc)
    : order(0)
    , traj_id(0)
    , knots(_alloc)
    , pts(_alloc)
    , start_time()  {
  (void)_alloc;
    }



   typedef int32_t _order_type;
  _order_type order;

   typedef int64_t _traj_id_type;
  _traj_id_type traj_id;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _knots_type;
  _knots_type knots;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _pts_type;
  _pts_type pts;

   typedef ros::Time _start_time_type;
  _start_time_type start_time;





  typedef boost::shared_ptr< ::robot_communication::Bspline_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::Bspline_<ContainerAllocator> const> ConstPtr;

}; // struct Bspline_

typedef ::robot_communication::Bspline_<std::allocator<void> > Bspline;

typedef boost::shared_ptr< ::robot_communication::Bspline > BsplinePtr;
typedef boost::shared_ptr< ::robot_communication::Bspline const> BsplineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::Bspline_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::Bspline_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::Bspline_<ContainerAllocator1> & lhs, const ::robot_communication::Bspline_<ContainerAllocator2> & rhs)
{
  return lhs.order == rhs.order &&
    lhs.traj_id == rhs.traj_id &&
    lhs.knots == rhs.knots &&
    lhs.pts == rhs.pts &&
    lhs.start_time == rhs.start_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::Bspline_<ContainerAllocator1> & lhs, const ::robot_communication::Bspline_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::Bspline_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::Bspline_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::Bspline_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::Bspline_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::Bspline_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::Bspline_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::Bspline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ae0a2f5019a8a20108147f57eefee55";
  }

  static const char* value(const ::robot_communication::Bspline_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ae0a2f5019a8a20ULL;
  static const uint64_t static_value2 = 0x108147f57eefee55ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::Bspline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/Bspline";
  }

  static const char* value(const ::robot_communication::Bspline_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::Bspline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 order\n"
"int64 traj_id\n"
"float64[] knots\n"
"geometry_msgs/Point[] pts\n"
"time start_time\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::robot_communication::Bspline_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::Bspline_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order);
      stream.next(m.traj_id);
      stream.next(m.knots);
      stream.next(m.pts);
      stream.next(m.start_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bspline_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::Bspline_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::Bspline_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "order: ";
    Printer<int32_t>::stream(s, indent + "  ", v.order);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "traj_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.traj_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "knots: ";
    if (v.knots.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.knots.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.knots[i]);
    }
    if (v.knots.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pts: ";
    if (v.pts.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.pts.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.pts[i]);
    }
    if (v.pts.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "start_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_BSPLINE_H
