// Generated by gencpp from file robot_communication/chassisControl.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_CHASSISCONTROL_H
#define ROBOT_COMMUNICATION_MESSAGE_CHASSISCONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_communication
{
template <class ContainerAllocator>
struct chassisControl_
{
  typedef chassisControl_<ContainerAllocator> Type;

  chassisControl_()
    : xSpeed(0.0)
    , ySpeed(0.0)
    , chassisAngle(0.0)
    , chassisGyro(0.0)
    , timeStamp(0)
    , globalOrlocal(false)  {
    }
  chassisControl_(const ContainerAllocator& _alloc)
    : xSpeed(0.0)
    , ySpeed(0.0)
    , chassisAngle(0.0)
    , chassisGyro(0.0)
    , timeStamp(0)
    , globalOrlocal(false)  {
  (void)_alloc;
    }



   typedef float _xSpeed_type;
  _xSpeed_type xSpeed;

   typedef float _ySpeed_type;
  _ySpeed_type ySpeed;

   typedef float _chassisAngle_type;
  _chassisAngle_type chassisAngle;

   typedef float _chassisGyro_type;
  _chassisGyro_type chassisGyro;

   typedef uint32_t _timeStamp_type;
  _timeStamp_type timeStamp;

   typedef uint8_t _globalOrlocal_type;
  _globalOrlocal_type globalOrlocal;





  typedef boost::shared_ptr< ::robot_communication::chassisControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::chassisControl_<ContainerAllocator> const> ConstPtr;

}; // struct chassisControl_

typedef ::robot_communication::chassisControl_<std::allocator<void> > chassisControl;

typedef boost::shared_ptr< ::robot_communication::chassisControl > chassisControlPtr;
typedef boost::shared_ptr< ::robot_communication::chassisControl const> chassisControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::chassisControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::chassisControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::chassisControl_<ContainerAllocator1> & lhs, const ::robot_communication::chassisControl_<ContainerAllocator2> & rhs)
{
  return lhs.xSpeed == rhs.xSpeed &&
    lhs.ySpeed == rhs.ySpeed &&
    lhs.chassisAngle == rhs.chassisAngle &&
    lhs.chassisGyro == rhs.chassisGyro &&
    lhs.timeStamp == rhs.timeStamp &&
    lhs.globalOrlocal == rhs.globalOrlocal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::chassisControl_<ContainerAllocator1> & lhs, const ::robot_communication::chassisControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::chassisControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::chassisControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::chassisControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::chassisControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::chassisControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::chassisControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::chassisControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba44848e12b315b92df95a3f875577ab";
  }

  static const char* value(const ::robot_communication::chassisControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba44848e12b315b9ULL;
  static const uint64_t static_value2 = 0x2df95a3f875577abULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::chassisControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/chassisControl";
  }

  static const char* value(const ::robot_communication::chassisControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::chassisControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 导航发布的消息\n"
"#全局x轴线速度\n"
"float32 xSpeed \n"
"#全局y轴线速度\n"
"float32 ySpeed\n"
"#底盘角度\n"
"float32 chassisAngle\n"
"#底盘角速度\n"
"float32 chassisGyro\n"
"# 时间戳\n"
"uint32 timeStamp\n"
"# 标志位局部控制还是全局控制\n"
"bool globalOrlocal\n"
;
  }

  static const char* value(const ::robot_communication::chassisControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::chassisControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xSpeed);
      stream.next(m.ySpeed);
      stream.next(m.chassisAngle);
      stream.next(m.chassisGyro);
      stream.next(m.timeStamp);
      stream.next(m.globalOrlocal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chassisControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::chassisControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::chassisControl_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "xSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.xSpeed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ySpeed: ";
    Printer<float>::stream(s, indent + "  ", v.ySpeed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "chassisAngle: ";
    Printer<float>::stream(s, indent + "  ", v.chassisAngle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "chassisGyro: ";
    Printer<float>::stream(s, indent + "  ", v.chassisGyro);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timeStamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeStamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "globalOrlocal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.globalOrlocal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_CHASSISCONTROL_H
