// Generated by gencpp from file robot_communication/ESDFmap.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_ESDFMAP_H
#define ROBOT_COMMUNICATION_MESSAGE_ESDFMAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_communication
{
template <class ContainerAllocator>
struct ESDFmap_
{
  typedef ESDFmap_<ContainerAllocator> Type;

  ESDFmap_()
    : origin_x(0.0)
    , origin_y(0.0)
    , resolution(0.0)
    , width(0.0)
    , height(0.0)
    , data()  {
    }
  ESDFmap_(const ContainerAllocator& _alloc)
    : origin_x(0.0)
    , origin_y(0.0)
    , resolution(0.0)
    , width(0.0)
    , height(0.0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef float _origin_x_type;
  _origin_x_type origin_x;

   typedef float _origin_y_type;
  _origin_y_type origin_y;

   typedef float _resolution_type;
  _resolution_type resolution;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::robot_communication::ESDFmap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::ESDFmap_<ContainerAllocator> const> ConstPtr;

}; // struct ESDFmap_

typedef ::robot_communication::ESDFmap_<std::allocator<void> > ESDFmap;

typedef boost::shared_ptr< ::robot_communication::ESDFmap > ESDFmapPtr;
typedef boost::shared_ptr< ::robot_communication::ESDFmap const> ESDFmapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::ESDFmap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::ESDFmap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::ESDFmap_<ContainerAllocator1> & lhs, const ::robot_communication::ESDFmap_<ContainerAllocator2> & rhs)
{
  return lhs.origin_x == rhs.origin_x &&
    lhs.origin_y == rhs.origin_y &&
    lhs.resolution == rhs.resolution &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::ESDFmap_<ContainerAllocator1> & lhs, const ::robot_communication::ESDFmap_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::ESDFmap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::ESDFmap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::ESDFmap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::ESDFmap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::ESDFmap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::ESDFmap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::ESDFmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a84df51ecdc0540548c40df5f4deb13";
  }

  static const char* value(const ::robot_communication::ESDFmap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a84df51ecdc0540ULL;
  static const uint64_t static_value2 = 0x548c40df5f4deb13ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::ESDFmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/ESDFmap";
  }

  static const char* value(const ::robot_communication::ESDFmap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::ESDFmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 栅格地图的原点x值(相对世界坐标系),单位为m\n"
"float32 origin_x\n"
"# 栅格地图的原点y值(相对世界坐标系),单位为m\n"
"float32 origin_y\n"
"# 栅格地图的分辨率\n"
"float32 resolution\n"
"# 栅格地图的宽\n"
"float32 width\n"
"# 栅格地图的高\n"
"float32 height\n"
"\n"
"# 一维数组，数组内的数据表示为对应栅格的占用概率。\n"
"# 栅格地图中每一个小格的坐标对应一维数组中的一个数据。\n"
"# 栅格数据大小代表当前点到障碍物的距离数值\n"
"# -值表示未知区域\n"
"int32[] data\n"
;
  }

  static const char* value(const ::robot_communication::ESDFmap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::ESDFmap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.origin_x);
      stream.next(m.origin_y);
      stream.next(m.resolution);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ESDFmap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::ESDFmap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::ESDFmap_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "origin_x: ";
    Printer<float>::stream(s, indent + "  ", v.origin_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "origin_y: ";
    Printer<float>::stream(s, indent + "  ", v.origin_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_ESDFMAP_H
