// Generated by gencpp from file robot_communication/goal.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_GOAL_H
#define ROBOT_COMMUNICATION_MESSAGE_GOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_communication
{
template <class ContainerAllocator>
struct goal_
{
  typedef goal_<ContainerAllocator> Type;

  goal_()
    : Position_x(0.0)
    , Position_y(0.0)
    , Position_yaw(0.0)  {
    }
  goal_(const ContainerAllocator& _alloc)
    : Position_x(0.0)
    , Position_y(0.0)
    , Position_yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _Position_x_type;
  _Position_x_type Position_x;

   typedef float _Position_y_type;
  _Position_y_type Position_y;

   typedef float _Position_yaw_type;
  _Position_yaw_type Position_yaw;





  typedef boost::shared_ptr< ::robot_communication::goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::goal_<ContainerAllocator> const> ConstPtr;

}; // struct goal_

typedef ::robot_communication::goal_<std::allocator<void> > goal;

typedef boost::shared_ptr< ::robot_communication::goal > goalPtr;
typedef boost::shared_ptr< ::robot_communication::goal const> goalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::goal_<ContainerAllocator1> & lhs, const ::robot_communication::goal_<ContainerAllocator2> & rhs)
{
  return lhs.Position_x == rhs.Position_x &&
    lhs.Position_y == rhs.Position_y &&
    lhs.Position_yaw == rhs.Position_yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::goal_<ContainerAllocator1> & lhs, const ::robot_communication::goal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "529b653ff7a616d53e93e8d91f1e84eb";
  }

  static const char* value(const ::robot_communication::goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x529b653ff7a616d5ULL;
  static const uint64_t static_value2 = 0x3e93e8d91f1e84ebULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/goal";
  }

  static const char* value(const ::robot_communication::goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 目标点信息\n"
"# x位置信息\n"
"float32 Position_x\n"
"# y位置信息\n"
"float32 Position_y\n"
"# yaw轴角度信息\n"
"float32 Position_yaw\n"
;
  }

  static const char* value(const ::robot_communication::goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Position_x);
      stream.next(m.Position_y);
      stream.next(m.Position_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::goal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Position_x: ";
    Printer<float>::stream(s, indent + "  ", v.Position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Position_y: ";
    Printer<float>::stream(s, indent + "  ", v.Position_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Position_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.Position_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_GOAL_H
