// Generated by gencpp from file robot_communication/localizationInfoBroadcast.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_LOCALIZATIONINFOBROADCAST_H
#define ROBOT_COMMUNICATION_MESSAGE_LOCALIZATIONINFOBROADCAST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_communication
{
template <class ContainerAllocator>
struct localizationInfoBroadcast_
{
  typedef localizationInfoBroadcast_<ContainerAllocator> Type;

  localizationInfoBroadcast_()
    : xPosition(0.0)
    , yPosition(0.0)
    , xSpeed(0.0)
    , ySpeed(0.0)
    , xAccel(0.0)
    , yAccel(0.0)
    , chassisAngle(0.0)
    , chassisGyro(0.0)
    , timeStamp(0)  {
    }
  localizationInfoBroadcast_(const ContainerAllocator& _alloc)
    : xPosition(0.0)
    , yPosition(0.0)
    , xSpeed(0.0)
    , ySpeed(0.0)
    , xAccel(0.0)
    , yAccel(0.0)
    , chassisAngle(0.0)
    , chassisGyro(0.0)
    , timeStamp(0)  {
  (void)_alloc;
    }



   typedef float _xPosition_type;
  _xPosition_type xPosition;

   typedef float _yPosition_type;
  _yPosition_type yPosition;

   typedef float _xSpeed_type;
  _xSpeed_type xSpeed;

   typedef float _ySpeed_type;
  _ySpeed_type ySpeed;

   typedef float _xAccel_type;
  _xAccel_type xAccel;

   typedef float _yAccel_type;
  _yAccel_type yAccel;

   typedef float _chassisAngle_type;
  _chassisAngle_type chassisAngle;

   typedef float _chassisGyro_type;
  _chassisGyro_type chassisGyro;

   typedef uint32_t _timeStamp_type;
  _timeStamp_type timeStamp;





  typedef boost::shared_ptr< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> const> ConstPtr;

}; // struct localizationInfoBroadcast_

typedef ::robot_communication::localizationInfoBroadcast_<std::allocator<void> > localizationInfoBroadcast;

typedef boost::shared_ptr< ::robot_communication::localizationInfoBroadcast > localizationInfoBroadcastPtr;
typedef boost::shared_ptr< ::robot_communication::localizationInfoBroadcast const> localizationInfoBroadcastConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::localizationInfoBroadcast_<ContainerAllocator1> & lhs, const ::robot_communication::localizationInfoBroadcast_<ContainerAllocator2> & rhs)
{
  return lhs.xPosition == rhs.xPosition &&
    lhs.yPosition == rhs.yPosition &&
    lhs.xSpeed == rhs.xSpeed &&
    lhs.ySpeed == rhs.ySpeed &&
    lhs.xAccel == rhs.xAccel &&
    lhs.yAccel == rhs.yAccel &&
    lhs.chassisAngle == rhs.chassisAngle &&
    lhs.chassisGyro == rhs.chassisGyro &&
    lhs.timeStamp == rhs.timeStamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::localizationInfoBroadcast_<ContainerAllocator1> & lhs, const ::robot_communication::localizationInfoBroadcast_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93de7300af4a3e98ca0a4ec3c9466b01";
  }

  static const char* value(const ::robot_communication::localizationInfoBroadcast_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93de7300af4a3e98ULL;
  static const uint64_t static_value2 = 0xca0a4ec3c9466b01ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/localizationInfoBroadcast";
  }

  static const char* value(const ::robot_communication::localizationInfoBroadcast_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 定位消息广播需要数据\n"
"# 全局x位置\n"
"float32 xPosition\n"
"# 全局y位置\n"
"float32 yPosition\n"
"#全局x轴线速度\n"
"float32 xSpeed \n"
"#全局y轴线速度\n"
"float32 ySpeed\n"
"#车体x加速度\n"
"float32 xAccel \n"
"#车体y加速度\n"
"float32 yAccel\n"
"#底盘角度\n"
"float32 chassisAngle\n"
"#底盘角速度\n"
"float32 chassisGyro\n"
"# 时间戳\n"
"uint32 timeStamp\n"
"\n"
;
  }

  static const char* value(const ::robot_communication::localizationInfoBroadcast_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xPosition);
      stream.next(m.yPosition);
      stream.next(m.xSpeed);
      stream.next(m.ySpeed);
      stream.next(m.xAccel);
      stream.next(m.yAccel);
      stream.next(m.chassisAngle);
      stream.next(m.chassisGyro);
      stream.next(m.timeStamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct localizationInfoBroadcast_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::localizationInfoBroadcast_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::localizationInfoBroadcast_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "xPosition: ";
    Printer<float>::stream(s, indent + "  ", v.xPosition);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yPosition: ";
    Printer<float>::stream(s, indent + "  ", v.yPosition);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.xSpeed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ySpeed: ";
    Printer<float>::stream(s, indent + "  ", v.ySpeed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xAccel: ";
    Printer<float>::stream(s, indent + "  ", v.xAccel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yAccel: ";
    Printer<float>::stream(s, indent + "  ", v.yAccel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "chassisAngle: ";
    Printer<float>::stream(s, indent + "  ", v.chassisAngle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "chassisGyro: ";
    Printer<float>::stream(s, indent + "  ", v.chassisGyro);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timeStamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeStamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_LOCALIZATIONINFOBROADCAST_H
