// Generated by gencpp from file robot_communication/sensorData.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_SENSORDATA_H
#define ROBOT_COMMUNICATION_MESSAGE_SENSORDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_communication
{
template <class ContainerAllocator>
struct sensorData_
{
  typedef sensorData_<ContainerAllocator> Type;

  sensorData_()
    : local_x_Veloc(0.0)
    , local_y_Veloc(0.0)
    , local_x_Accel(0.0)
    , local_y_Accel(0.0)
    , yaw(0.0)
    , timeStamp_10us(0)  {
    }
  sensorData_(const ContainerAllocator& _alloc)
    : local_x_Veloc(0.0)
    , local_y_Veloc(0.0)
    , local_x_Accel(0.0)
    , local_y_Accel(0.0)
    , yaw(0.0)
    , timeStamp_10us(0)  {
  (void)_alloc;
    }



   typedef float _local_x_Veloc_type;
  _local_x_Veloc_type local_x_Veloc;

   typedef float _local_y_Veloc_type;
  _local_y_Veloc_type local_y_Veloc;

   typedef float _local_x_Accel_type;
  _local_x_Accel_type local_x_Accel;

   typedef float _local_y_Accel_type;
  _local_y_Accel_type local_y_Accel;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef uint32_t _timeStamp_10us_type;
  _timeStamp_10us_type timeStamp_10us;





  typedef boost::shared_ptr< ::robot_communication::sensorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::sensorData_<ContainerAllocator> const> ConstPtr;

}; // struct sensorData_

typedef ::robot_communication::sensorData_<std::allocator<void> > sensorData;

typedef boost::shared_ptr< ::robot_communication::sensorData > sensorDataPtr;
typedef boost::shared_ptr< ::robot_communication::sensorData const> sensorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::sensorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::sensorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::sensorData_<ContainerAllocator1> & lhs, const ::robot_communication::sensorData_<ContainerAllocator2> & rhs)
{
  return lhs.local_x_Veloc == rhs.local_x_Veloc &&
    lhs.local_y_Veloc == rhs.local_y_Veloc &&
    lhs.local_x_Accel == rhs.local_x_Accel &&
    lhs.local_y_Accel == rhs.local_y_Accel &&
    lhs.yaw == rhs.yaw &&
    lhs.timeStamp_10us == rhs.timeStamp_10us;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::sensorData_<ContainerAllocator1> & lhs, const ::robot_communication::sensorData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::sensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::sensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::sensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::sensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::sensorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::sensorData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::sensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b6cc02982ebe7cd38d12aed40230509";
  }

  static const char* value(const ::robot_communication::sensorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b6cc02982ebe7cdULL;
  static const uint64_t static_value2 = 0x38d12aed40230509ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::sensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/sensorData";
  }

  static const char* value(const ::robot_communication::sensorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::sensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#接收到下位机发送的消息，轮速计、IMU、时间戳等\n"
"#局部速度\n"
"float32 local_x_Veloc\n"
"float32 local_y_Veloc\n"
"#局部加速度\n"
"float32 local_x_Accel\n"
"float32 local_y_Accel\n"
"#yaw轴数值\n"
"float32 yaw\n"
"#时间戳 10us是时间戳的分辨率\n"
"uint32 timeStamp_10us\n"
;
  }

  static const char* value(const ::robot_communication::sensorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::sensorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.local_x_Veloc);
      stream.next(m.local_y_Veloc);
      stream.next(m.local_x_Accel);
      stream.next(m.local_y_Accel);
      stream.next(m.yaw);
      stream.next(m.timeStamp_10us);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::sensorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::sensorData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "local_x_Veloc: ";
    Printer<float>::stream(s, indent + "  ", v.local_x_Veloc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_y_Veloc: ";
    Printer<float>::stream(s, indent + "  ", v.local_y_Veloc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_x_Accel: ";
    Printer<float>::stream(s, indent + "  ", v.local_x_Accel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_y_Accel: ";
    Printer<float>::stream(s, indent + "  ", v.local_y_Accel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timeStamp_10us: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeStamp_10us);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_SENSORDATA_H
